In [7]:
import pandas as pd
s = pd.Series(list('PQR'))
pd.get_dummies(s)

P      Q      R
0   True  False  False
1  False   True  False
2  False  False   True

In [8]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [9]:
# define example
data = ['ice', 'ice', 'fire', 'ice', 'sun', 'sun', 'fire', 'ice', 'fire', 'sun']

print("cold-0, hot-1, warm-2")
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

cold-0, hot-1, warm-2
['ice' 'ice' 'fire' 'ice' 'sun' 'sun' 'fire' 'ice' 'fire' 'sun']
[1 1 0 1 2 2 0 1 0 2]
[[0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
['ice']


c:\Users\heman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
